DROP DATABASE IF EXISTS `recorte_de_coracao`;
CREATE DATABASE `recorte_de_coracao` CHAR SET 'utf16';

USE `recorte_de_coracao`;

SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS `PERSON` (
	`PERSONID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `PERSONTYPE` INT,
    `NAME` VARCHAR(300),
    `CPF` VARCHAR(300),
    `RG` VARCHAR(300),
    `BIRTHDATE` DATE,
    `CEP` VARCHAR(300),
    `STREET` VARCHAR(300),
    `COMPLEMENT` VARCHAR(300),
    `OTHERLOCATION` TEXT,
    `EMAIL` VARCHAR(500),
    `PHONE` VARCHAR(300),
    `OTHERCONTACT` TEXT
);

CREATE TABLE `MODEL` (
	`MODELID`      INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `NAME`          VARCHAR(300)
);

CREATE TABLE `PRODUCT` (
	`PRODUCTID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `NAME`      VARCHAR(500),
    `VALUE`     DECIMAL(12,4)
);

CREATE TABLE `MODELPRODUCT` (
	`MODELID`      INT NOT NULL,
    `PRODUCTID`    INT NOT NULL,
    
    FOREIGN KEY (`MODELID`) REFERENCES `MODEL`(`MODELID`),
	FOREIGN KEY (`PRODUCTID`) REFERENCES `PRODUCT`(`PRODUCTID`),

    PRIMARY KEY (`MODELID`, `PRODUCTID`)
);

CREATE TABLE `FILE` (
	`FILEID`              INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `NAME`            VARCHAR(300) NOT NULL,
    `EXTENSION`        VARCHAR(300) NOT NULL,
    `LENGTH`         BIGINT UNSIGNED NOT NULL,
    `BINARY`         LONGBLOB NOT NULL
);

CREATE TABLE `PRODUCT_GALERY` (
	`FILEID` INT NOT NULL,
	`PRODUCTID` INT NOT NULL,
    
    FOREIGN KEY (`FILEID`) REFERENCES `FILE`(`FILEID`),
	FOREIGN KEY (`PRODUCTID`) REFERENCES `PRODUCT`(`PRODUCTID`),

    PRIMARY KEY (`FILEID`, `PRODUCTID`)    
);

SET FOREIGN_KEY_CHECKS = 1;