USE `recorte_de_coracao`;

SET FOREIGN_KEY_CHECKS=0;

# 55081995611216
DROP TABLE IF EXISTS `Arquivo`;
DROP TABLE IF EXISTS `Produto_Pedido`;
DROP TABLE IF EXISTS `Pedido`;
DROP TABLE IF EXISTS `Cliente`;
DROP TABLE IF EXISTS `Produto`;
DROP TABLE IF EXISTS `Pagamento`;

CREATE TABLE IF NOT EXISTS `Arquivo` (
	`Id` BIGINT NOT NULL AUTO_INCREMENT,
    `Nome` VARCHAR(300) NOT NULL,
    `Extensao` VARCHAR(300) NOT NULL,
    `Tamanho` BIGINT NOT NULL,
    `Binario` LONGBLOB NOT NULL,
    `Criado Em` DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(`Id`)
);

CREATE TABLE IF NOT EXISTS `Cliente` (
	`Id` BIGINT NOT NULL AUTO_INCREMENT,
    `Nome` VARCHAR(300) NOT NULL,
    `Email` VARCHAR(300) NOT NULL UNIQUE,
    `Telefone` BIGINT NOT NULL,
    `Criado Em` DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(`Id`)
);

CREATE TABLE IF NOT EXISTS `Produto` (
	`Id` BIGINT NOT NULL AUTO_INCREMENT,
    `Nome` VARCHAR(300) NOT NULL,
    `Valor Unitario` DECIMAL(18, 2) NOT NULL,
    `Imagem` BIGINT,
    `Criado Em` DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(`Imagem`) REFERENCES `Arquivo`(`Id`) ON DELETE SET NULL,
    PRIMARY KEY(`Id`)
);

CREATE TABLE IF NOT EXISTS `Pedido` (
	`Id` BIGINT NOT NULL AUTO_INCREMENT,
    `Cliente` BIGINT NOT NULL,
    `Data Entrega` DATETIME NOT NULL,
    `Data Pedido` DATETIME NOT NULL,
    `Status` INT NOT NULL,
    `Criado Em` DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(`Cliente`) REFERENCES `Cliente`(`Id`) ON DELETE RESTRICT,
    PRIMARY KEY(`Id`)
);

CREATE TABLE IF NOT EXISTS `Produto_Pedido` (
	`Id` BIGINT NOT NULL AUTO_INCREMENT,
    `Produto` BIGINT NOT NULL,
    `Pedido` BIGINT NOT NULL,
    `Quantidade` INT NOT NULL, 
    `Valor Total` DECIMAL(18,2) NOT NULL,
    `Criado Em` DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(`Produto`) REFERENCES `Produto`(`Id`) ON DELETE RESTRICT,
    FOREIGN KEY(`Pedido`) REFERENCES `Pedido`(`Id`) ON DELETE RESTRICT,
    PRIMARY KEY(`Id`)
);

CREATE TABLE IF NOT EXISTS `Pagamento` (
	`Id` BIGINT NOT NULL AUTO_INCREMENT,
    `Valor` DECIMAL(18,2) NOT NULL,
    `Status` INT NOT NULL, 
    `Pedido` BIGINT,
    `Comprovante` BIGINT,
    `Criado em` DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(`Comprovante`) REFERENCES `Arquivo`(`Id`) ON DELETE SET NULL,
    FOREIGN KEY(`Pedido`) REFERENCES `Pedido`(`Id`) ON DELETE RESTRICT,
    PRIMARY KEY(`Id`)
);

SET FOREIGN_KEY_CHECKS=1;